#ifndef FROSTNIP_PP_CONSTANTS_H
#define FROSTNIP_PP_CONSTANTS_H

#include <SDL.h>

const unsigned int FPS = 60;
const unsigned int FRAME_TARGET_TIME = (1000 / FPS);

const unsigned int WINDOW_WIDTH = 800;
const unsigned int WINDOW_HEIGHT = 600;

enum CollisionType {
	NO_COLLISION,
	PLAYER_ENEMY_COLLISION,
	PLAYER_PROJECTILE_COLLISION,
	ENEMY_PROJECTILE_COLLISION,
	PLAYER_VEGETATION_COLLISION,
	PLAYER_LEVEL_COMPLETE_COLLISION
};

enum LayerType {
	TILEMAP_LAYER,
	VEGETATION_LAYER,
	ENEMY_LAYER,
	PLAYER_LAYER,
	PROJECTILE_LAYER,
	UI_LAYER
};

const unsigned int NUM_LAYERS = 6;

const SDL_Color WHITE = {255, 255, 255, 255};
const SDL_Color GREEN = {0, 255, 0, 255};

#endif //FROSTNIP_PP_CONSTANTS_H
