#ifndef FROSTNIP_PP_CONSTANTS_H
#define FROSTNIP_PP_CONSTANTS_H

#define FPS 60
#define FRAME_TARGET_TIME (1000 / FPS)

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

enum CollisionType {
	NO_COLLISION,
	PLAYER_ENEMY_COLLISION,
	PLAYER_PROJECTILE_COLLISION,
	ENEMY_PROJECTILE_COLLISION,
	PLAYER_VEGETATION_COLLISION,
	PLAYER_LEVEL_COMPLETE_COLLISION
};

enum LayerType {
	TILEMAP_LAYER,
	VEGETATION_LAYER,
	ENEMY_LAYER,
	PLAYER_LAYER,
	PROJECTILE_LAYER,
	UI_LAYER
};

const unsigned int NUM_LAYERS = 6;

#endif //FROSTNIP_PP_CONSTANTS_H
