#ifndef FROSTNIP_PP_CONSTANTS_H
#define FROSTNIP_PP_CONSTANTS_H

#define FPS 60
#define FRAME_TARGET_TIME (1000 / FPS)

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

#define DEBUG false

enum LayerType {
	TILEMAP_LAYER = 0,
	VEGETATION_LAYER,
	ENEMY_LAYER,
	PLAYER_LAYER,
	PROJECTILE_LAYER,
	UI_LAYER
};

const unsigned int NUM_LAYERS = 6;

#endif //FROSTNIP_PP_CONSTANTS_H
